// <auto-generated />
using System;
using BankaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankaAPI.Migrations
{
    [DbContext(typeof(BankaDbContext))]
    [Migration("20250722084027_CorrectMusteriNoRelationship")]
    partial class CorrectMusteriNoRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankaAPI.Models.Musteri", b =>
                {
                    b.Property<int>("MusteriNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusteriNo"));

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cinsiyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KrediNotu")
                        .HasColumnType("int");

                    b.Property<decimal?>("KrediTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sube")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MusteriNo");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("BankaAPI.Models.OdemeLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MusteriNo")
                        .HasColumnType("int");

                    b.Property<int?>("MusteriNoNavigationMusteriNo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("OdemeTutari")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LogId");

                    b.HasIndex("MusteriNoNavigationMusteriNo");

                    b.ToTable("OdemeLoglari");
                });

            modelBuilder.Entity("BankaAPI.Models.Odemeler", b =>
                {
                    b.Property<int>("OdemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OdemeId"));

                    b.Property<decimal?>("GecikmisBorcTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GuncelBorcTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GuncelOdemeTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MusteriNo")
                        .HasColumnType("int");

                    b.Property<decimal?>("OdenmisBorcTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("SonOdemeTarihi")
                        .HasColumnType("date");

                    b.HasKey("OdemeId");

                    b.HasIndex("MusteriNo");

                    b.ToTable("Odemeler");
                });

            modelBuilder.Entity("BankaAPI.Models.OdemeLog", b =>
                {
                    b.HasOne("BankaAPI.Models.Musteri", "MusteriNoNavigation")
                        .WithMany("OdemeLogs")
                        .HasForeignKey("MusteriNoNavigationMusteriNo");

                    b.Navigation("MusteriNoNavigation");
                });

            modelBuilder.Entity("BankaAPI.Models.Odemeler", b =>
                {
                    b.HasOne("BankaAPI.Models.Musteri", null)
                        .WithMany("Odemelers")
                        .HasForeignKey("MusteriNo")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("BankaAPI.Models.Musteri", b =>
                {
                    b.Navigation("OdemeLogs");

                    b.Navigation("Odemelers");
                });
#pragma warning restore 612, 618
        }
    }
}
