// <auto-generated />
using System;
using BankaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankaAPI.Migrations
{
    [DbContext(typeof(BankaDbContext))]
    partial class BankaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankaAPI.Models.Musteri", b =>
                {
                    b.Property<int>("MusteriNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusteriNo"));

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cinsiyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KrediNotu")
                        .HasColumnType("int");

                    b.Property<decimal?>("KrediTutari")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sube")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MusteriNo");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("BankaAPI.Models.OdemeLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MusteriNo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("OdemeTutari")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LogId");

                    b.HasIndex("MusteriNo");

                    b.ToTable("OdemeLog");
                });

            modelBuilder.Entity("BankaAPI.Models.Odemeler", b =>
                {
                    b.Property<int>("OdemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OdemeId"));

                    b.Property<decimal?>("GecikmisBorcTutari")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GuncelBorcTutari")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GuncelOdemeTutari")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MusteriNo")
                        .HasColumnType("int");

                    b.Property<decimal?>("OdenmisBorcTutari")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("SonOdemeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("OdemeId");

                    b.HasIndex("MusteriNo");

                    b.ToTable("Odemeler");
                });

            modelBuilder.Entity("BankaAPI.Models.OdemeLog", b =>
                {
                    b.HasOne("BankaAPI.Models.Musteri", "Musteri")
                        .WithMany("OdemeLog")
                        .HasForeignKey("MusteriNo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("BankaAPI.Models.Odemeler", b =>
                {
                    b.HasOne("BankaAPI.Models.Musteri", "Musteri")
                        .WithMany("Odemeler")
                        .HasForeignKey("MusteriNo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("BankaAPI.Models.Musteri", b =>
                {
                    b.Navigation("OdemeLog");

                    b.Navigation("Odemeler");
                });
#pragma warning restore 612, 618
        }
    }
}
